# docker-compose.yaml

version: '3.9'

services:
  very-simple-upload-server:
    build:
      context: .
      dockerfile: Dockerfile.upload-server
    image: very_simple_upload_server
    container_name: very-simple-upload-server
    environment:
      - very-simple-uuid-token=0dcac178-d084-4313-be7c-330a4c9f0867
    volumes:
      - ./data:/uploads
    restart: unless-stopped
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'app' || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5

  very-simple-messaging-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: very_simple_messaging_app
    container_name: very-simple-messaging-app
    environment:
      NTFY_TOPIC: '${NTFY_TOPIC}'
      NTFY_HOST: '${NTFY_HOST}'
      DEBUG: '${DEBUG}'
      ENV_TEST: '### inside docker-compose'
    volumes:
      - ./src:/src
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'very_simple_start_skript.py' || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
