# docker-compose.yaml

version: '3.9'

services:
  very-simple-upload-server:
    build:
      context: .
      dockerfile: Dockerfile.upload-server
    image: very-simple-upload-server
    container_name: very-simple-upload-server
    environment:
      - very-simple-uuid-token=0dcac178-d084-4313-be7c-330a4c9f0867
    volumes:
      - ./data:/uploads
    restart: unless-stopped
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'app' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  very-simple-messaging-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: very-simple-messaging-app
    container_name: very-simple-messaging-app
    env_file: .env
    environment:
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_HOST=${NTFY_HOST}
      - DEBUG=${DEBUG}
    volumes:
      - ./src:/src
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "docker container inspect --format='{{.State.Health.Status}}' very-simple-upload-server | grep -q 'healthy' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s