# docker-compose.override.test.yaml

version: '3.9'

services:
  very-simple-upload-server:
    ports:
      - "9090:80"
    volumes:
      - ./data_test:/uploads  # Verwenden Sie ein separates Verzeichnis für die CI-Umgebung
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f './app' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  very-simple-messaging-app:
    environment:
      NTFY_TOPIC: ${NTFY_TOPIC}
      NTFY_HOST: ${NTFY_HOST}
      DEBUG: ${DEBUG}
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'very_simple_start_skript.py' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

