# Dockerfile.upload-server

FROM alpine:3.17.3

COPY --from=hallotschuess/very-simple-upload-server:latest /server/app ./
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x entrypoint.sh
RUN chmod +x app

RUN mkdir -p /uploads && chmod 777 /uploads

RUN apk --no-cache add wget

RUN adduser --disabled-password --gecos '' very-simple-uploader
USER very-simple-uploader

HEALTHCHECK  --interval=5m --timeout=3s \
  CMD pgrep -f "app" || exit 1

ENTRYPOINT ["/entrypoint.sh", "./app"]