# Dockerfile.upload-server

FROM alpine:3.17.3

COPY --from=hallotschuess/very-simple-upload-server:latest /server/app ./
COPY entrypoint-upload-server.sh /entrypoint.sh

RUN chmod +x entrypoint.sh
RUN chmod +x app

RUN apk --no-cache add wget su-exec

HEALTHCHECK  --interval=5m --timeout=3s \
  CMD pgrep -f "app" || exit 1

ENTRYPOINT ["/entrypoint.sh", "./app"]
