# docker-compose.override.test.yaml

version: '3.9'

services:
  very-simple-upload-server:
    ports:
      - "9090:80"
    volumes:
      - ./data_test:/uploads

  very-simple-messaging-app:
    environment:
      NTFY_TOPIC: '${TEST_NTFY_TOPIC}'
    command: bash -c "export && exec python3 very_simple_start_skript.py"
