# docker-compose.override.test.yaml

version: '3.9'

services:
  very-simple-upload-server:
    volumes:
      - ./data_test:/uploads

  very-simple-messaging-app:
    environment:
      NTFY_TOPIC: ${NTFY_TOPIC:-}
