name: Lint with ruff
description: Run ruff linter on Python code
runs:
  using: composite
  steps:
    - run: |
        python -m pip install ruff
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
        ruff --format=github --target-version=py37 .
      shell: bash
