# .github/workflows/python.yml

name: Python application test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images
      run: docker-compose build

  unittests:
    runs-on: ubuntu-latest
    needs: build_images
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python and install dependencies
      uses: ./.github/actions/setup-python-dependencies
      with:
        requirements: requirements.txt
    - name: Run unittests
      run: |
        pytest --junitxml=unittest-results.xml tests/test_instance.py tests/test_very_simple_start_skript.py

  integration_tests:
    runs-on: ubuntu-latest
    needs: build_images
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python and install dependencies
      uses: ./.github/actions/setup-python-dependencies
      with:
        requirements: requirements.txt
    - name: Set environment variables
      run: |
        echo "DEBUG=false" >> $GITHUB_ENV
        echo "NTFY_TOPIC=" >> $GITHUB_ENV
    - name: Run integration tests
      env:
        CI: true
      run: |
        pytest --junitxml=integration-test-results.xml tests/integration_test.py
