# .github/workflows/python.yml

name: Python application test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo docker --version
    - name: Set environment variables
      run: |
        echo "NTFY_HOST=https://ntfy.sh" >> $GITHUB_ENV
        echo "DEBUG=true" >> $GITHUB_ENV
        echo "NTFY_TOPIC=" >> $GITHUB_ENV
    - name: Build Docker Images
      run: |
        docker-compose --file docker-compose.yaml --file docker-compose.override.test.yaml build
    - name: Run tests
      run: |
        pytest tests/
