# .github/workflows/python.yml

name: Python application test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images
      run: docker-compose build

  unittests:
    runs-on: ubuntu-latest
    needs: build_images
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python and install dependencies
      uses: ./.github/actions/setup-python-dependencies
      with:
        requirements: requirements.txt
    - name: Run unittests - test_instance
      run: pytest -s --junitxml=unittest-results.xml tests/test_instance.py
    - name: Run unittests - test_very_simple_start_skript
      run: pytest -s --junitxml=unittest-results.xml tests/test_very_simple_start_skript.py
    - name: Archive unittest-results.xml
      uses: actions/upload-artifact@v2
      with:
        name: unittest-results
        path: unittest-results.xml

  integration_tests:
    runs-on: ubuntu-latest
    needs: build_images
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python and install dependencies
      uses: ./.github/actions/setup-python-dependencies
      with:
        requirements: requirements.txt
    - name: Run integration tests
      env:
        CI: true
      run: |
        pytest -s --junitxml=integration-test-results.xml tests/integration_test.py
    - name: Archive integration-test-results.xml
      uses: actions/upload-artifact@v2
      with:
        name: integration-test-results
        path: integration-test-results.xml
