# .github/workflows/python.yml

name: Python application test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo docker --version
    - name: Build Docker Images
      run: |
        docker-compose --file docker-compose.yaml --file docker-compose.override.test.yaml build

  unittests:
    runs-on: ubuntu-latest
    needs: build_images
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unittests
      run: |
        pytest --junitxml=unittest-results.xml tests/test_instance.py tests/test_very_simple_start_skript.py

  integration_tests:
    runs-on: ubuntu-latest
    needs: build_images
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set environment variables
      run: |
        echo "DEBUG=true" >> $GITHUB_ENV
        echo "NTFY_TOPIC=" >> $GITHUB_ENV  # Set a value here, or use an env variable from the repository or GitHub Secrets
    - name: Run integration tests
      run: |
        pytest --junitxml=integration-test-results.xml tests/integration_test.py
  
